language: node_js
script: ./scripts/package
before_deploy:
    # Set up git user name and tag this commit
    - git config --local user.name "Marco Gulino"
    - git config --local user.email "marco@gulinux.net"
    - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
    - git tag $TRAVIS_TAG
deploy:
    provider: releases
    api_key: "$GITHUB_TOKEN"
    file: build/*.tar.gz
    skip_cleanup: true
