#!/bin/bash
export FLASK_ENV=development

usage() {
    cat >&2 <<EOF
Usage: $0 [-m|--mock-gpio] [-- flask-arguments]
EOF
    exit 1
}

while [ -n "$1" ] && [ "$1" != "--" ]; do
    case "$1" in
        -m|--mock-gpio)
            export GPIOZERO_PIN_FACTORY=mock
            ;;
        *)
            usage
            ;;
    esac
    shift
done

./start-server --reload "$@"
