#!/usr/bin/env bash
if [[ -z "$PROJECT_VERSION" ]]; then
    echo "ERROR: PROJECT_VERSION variable not defined" >&2
    exit 1
fi
if [[ -z "$PACKAGE_TAG" ]]; then
    echo "ERROR: PACKAGE_TAG variable not defined" >&2
    exit 1
fi
PACKAGE_ARCHIVE="zwift-autofan-${PROJECT_VERSION}-${PACKAGE_TAG}.tar.gz"
if [[ ! -r "build/$PACKAGE_ARCHIVE" ]]; then
    echo "ERROR: package archive $PACKAGE_ARCHIVE not present please run the \`package\` script first" >&2
    exit 1
fi
cd build
PACKAGE_ROOTDIR="zwift-autofan_$PROJECT_VERSION-$PACKAGE_TAG"
DESTDIR="${PACKAGE_ROOTDIR}/usr/lib"
rm -rf "$DESTDIR"
mkdir -p "$DESTDIR"
tar xzf "$PACKAGE_ARCHIVE" -C "$DESTDIR"
mkdir -p "${PACKAGE_ROOTDIR}/etc/nginx/sites-available"
SKIP_NGINX_RESTART=true ../scripts/setup-nginx /usr/lib/zwift-autofan ${PACKAGE_ROOTDIR}/etc/nginx ../zwift-autofan.nginx.conf
mkdir -p "$PACKAGE_ROOTDIR/DEBIAN"
cat >"$PACKAGE_ROOTDIR/DEBIAN/control" <<EOF
Package: zwift-autofan
Version: ${PROJECT_VERSION}-${PACKAGE_TAG}
Section: base
Priority: optional
Architecture: all
Depends: nginx, python3, python3-pip, python3-flask, gunicorn, python3-gunicorn, debconf
Maintainer: Marco Gulino <marco@gulinux.net>
Description: Zwift Autofan
 Automatically change fan speed with Zwift APIs and web interface
EOF
cat > "$PACKAGE_ROOTDIR/DEBIAN/config" <<'EOF'
#!/bin/sh -e
. /usr/share/debconf/confmodule
db_input critical zwift-autofan/configure_nginx || true
db_go
EOF
chmod a+x $PACKAGE_ROOTDIR/DEBIAN/config

cat > "$PACKAGE_ROOTDIR/DEBIAN/postrm" <<'EOF'
#!/bin/sh -e
if [ -r /usr/share/debconf/confmodule ]; then
    . /usr/share/debconf/confmodule
    db_reset zwift-autofan/configure_nginx || true
fi
if [ "$1" = "purge" ]; then
    userdel zwift-autofan
    rm -f /etc/nginx/sites-enabled/zwift-autofan.nginx.conf
fi
if [ "$1" = "purge" -a -e /usr/share/debconf/confmodule ]; then
    # Source debconf library.
    . /usr/share/debconf/confmodule
    # Remove my changes to the db.
    db_purge
fi
EOF
chmod a+x $PACKAGE_ROOTDIR/DEBIAN/postrm

cat >"$PACKAGE_ROOTDIR/DEBIAN/postinst" <<'EOF'
#!/bin/sh -e
set -e
. /usr/share/debconf/confmodule

adduser --system zwift-autofan
gpasswd -a zwift-autofan gpio

db_get zwift-autofan/configure_nginx 
if [ "$RET" = "true" ]; then
    rm -f /etc/nginx/sites-enabled/*
    ln -s /etc/nginx/sites-available/zwift-autofan.nginx.conf /etc/nginx/sites-enabled
fi
EOF
chmod a+x $PACKAGE_ROOTDIR/DEBIAN/postinst

cat >"$PACKAGE_ROOTDIR/DEBIAN/templates" <<'EOF'
Template: zwift-autofan/configure_nginx
Type: boolean
Description: Do you want to automatically configure Nginx?
 Please note that this will DISABLE all your enabled configuration files in /etc/nginx/sites-enabled
EOF


dpkg-deb --build "$PACKAGE_ROOTDIR"
[ -z "$DBG_PACKAGE" ] && rm -rf "$PACKAGE_ROOTDIR"
