#!/bin/bash
set -e
#rm -rf build
mkdir -p build
cd frontend
rm -rf build
npm install
npm run build
cd ..
tar czf build/zwift-autofan-$(date +%Y-%m-%dT%H-%M-%S).tar.gz \
    scripts \
    requirements.txt \
    *.py \
    frontend/build \
    zwift-autofan.nginx.conf \
    --transform 's/^/zwift-autofan\//g'

